# Generated by Django 4.1.7 on 2023-03-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=500, null=True, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=500, null=True, verbose_name='Email')),
                ('message', models.TextField(null=True, verbose_name='Message')),
                ('submitted_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
                'db_table': 'contact_list',
            },
        ),
    ]
