# Generated by Django 4.1.7 on 2023-05-02 05:48

import ckeditor_uploader.fields
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='Slug')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description')),
                ('organiser', models.CharField(max_length=200, verbose_name='Organiser Name')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact No')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('image', models.ImageField(null=True, upload_to='events/%Y/%m/%d/', verbose_name='Event Image 1')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Event Video 1')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=10, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Keywords')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events',
            },
        ),
    ]
