# Generated by Django 4.1.7 on 2023-05-02 05:48

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imgCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=500, null=True, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(help_text='Image Size: 500x500', null=True, upload_to='gallery/category/%Y/%m/%d/', verbose_name='Image')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=10, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name': 'List Photo Category',
                'verbose_name_plural': 'List Photo Categories',
                'db_table': 'picture-list',
            },
        ),
        migrations.CreateModel(
            name='vdoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=500, null=True, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(help_text='Image Size: 500x500', null=True, upload_to='gallery/video/%Y/%m/%d/', verbose_name='Image')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=10, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name': 'List Video Category',
                'verbose_name_plural': 'List Video Categories',
                'db_table': 'video-list',
            },
        ),
        migrations.CreateModel(
            name='vdoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('video_url', embed_video.fields.EmbedVideoField(null=True)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=10, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.vdocategory')),
            ],
            options={
                'verbose_name': 'List Videos',
                'verbose_name_plural': 'List Videos',
                'db_table': 'video-url-list',
            },
        ),
        migrations.CreateModel(
            name='imgGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('image', models.ImageField(null=True, upload_to='gallery/image/%Y/%m/%d/', verbose_name='Image')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=10, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.imgcategory')),
            ],
            options={
                'verbose_name': 'List Photos',
                'verbose_name_plural': 'List Photos',
                'db_table': 'image-list',
            },
        ),
    ]
