# Generated by Django 4.1.7 on 2023-05-02 05:48

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='adBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Home', 'Home'), ('General', 'General')], max_length=10, null=True, verbose_name='Type')),
                ('title', models.CharField(max_length=500, null=True, unique=True, verbose_name='Title')),
                ('image', models.ImageField(null=True, upload_to='adBlock/%Y/%m/%d/', verbose_name='Image')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=10, verbose_name='Status')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date')),
            ],
            options={
                'verbose_name': 'adBlock',
                'verbose_name_plural': 'adBlocks',
                'db_table': 'adBlock-list',
            },
        ),
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True, unique=True, verbose_name='Title')),
                ('txt1', models.CharField(max_length=500, null=True, unique=True, verbose_name='Small Text 1')),
                ('txt2', models.CharField(max_length=500, null=True, unique=True, verbose_name='Small Text 2')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('btn_txt', models.CharField(max_length=50, null=True, verbose_name='Button Text')),
                ('btn_url', models.URLField(max_length=500, null=True, verbose_name='Button URL')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=10, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
                'db_table': 'banner-list',
            },
        ),
        migrations.CreateModel(
            name='lyJournals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True, unique=True, verbose_name='Title')),
                ('image', models.ImageField(null=True, upload_to='journals/%Y/%m/%d/', verbose_name='Image')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=10, verbose_name='Status')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
                'db_table': 'journal-list',
            },
        ),
        migrations.CreateModel(
            name='pageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=500, unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(max_length=500, null=True, verbose_name='Page Short Description')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=10, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name': 'List Page Category',
                'verbose_name_plural': 'List Page Categories',
                'db_table': 'page-category-list',
            },
        ),
        migrations.CreateModel(
            name='TermPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=100, null=True, verbose_name='Slug')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=100, verbose_name='Status')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name': 'Term Page',
                'verbose_name_plural': 'Term Page',
                'db_table': 'term-page-list',
            },
        ),
        migrations.CreateModel(
            name='webSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('slogan', models.CharField(max_length=100, null=True, verbose_name='Slogan')),
                ('logo', models.ImageField(null=True, upload_to='settings/logo/%Y/%m/%d/', verbose_name='Logo')),
                ('logo_white', models.ImageField(null=True, upload_to='settings/logo/%Y/%m/%d/', verbose_name='White Logo')),
                ('logo_round', models.ImageField(null=True, upload_to='settings/logo/%Y/%m/%d/', verbose_name='Round Logo')),
                ('favicon', models.ImageField(null=True, upload_to='settings/logo/%Y/%m/%d/', verbose_name='Round Logo')),
                ('topBar_btnTxt', models.CharField(blank=True, max_length=100, null=True, verbose_name='TopBar Button Text')),
                ('topBar_text', models.CharField(max_length=100, null=True, verbose_name='TopBar Text')),
                ('topBar_status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=100, verbose_name='TopBar Status')),
                ('keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='Keywords')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Front-end Settings',
                'verbose_name_plural': 'Front-end Settings',
                'db_table': 'front-end-settings-list',
            },
        ),
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, null=True, verbose_name='Symbol')),
                ('startYear', models.CharField(max_length=6, null=True, verbose_name='Start Year')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Copyright Text')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Copyright',
                'verbose_name_plural': 'Copyright',
                'db_table': 'copyright-list',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('address', models.CharField(max_length=500, null=True, verbose_name='Address')),
                ('phone', models.CharField(max_length=500, null=True, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('map_url', models.TextField(null=True, verbose_name='Map URL')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Page',
                'db_table': 'contact-page-list',
            },
        ),
        migrations.CreateModel(
            name='bannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='banner/%Y/%m/%d/', verbose_name='Image')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=10, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.banner')),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Image',
                'db_table': 'banner-image-list',
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Page Title')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=100, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Keywords')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.pagecategory')),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
                'db_table': 'about-page-list',
            },
        ),
    ]
