# Generated by Django 4.1.7 on 2023-05-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'List About Page', 'verbose_name_plural': 'List About Page'},
        ),
        migrations.AlterModelOptions(
            name='pagecategory',
            options={'verbose_name': 'List About Page Category', 'verbose_name_plural': 'List About Page Categories'},
        ),
        migrations.RemoveField(
            model_name='websettings',
            name='topBar_btnTxt',
        ),
        migrations.RemoveField(
            model_name='websettings',
            name='topBar_status',
        ),
        migrations.RemoveField(
            model_name='websettings',
            name='topBar_text',
        ),
        migrations.AddField(
            model_name='websettings',
            name='fb_url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='websettings',
            name='ig_url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='websettings',
            name='li_url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='websettings',
            name='tw_url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Twitter'),
        ),
    ]
