# Generated by Django 4.1.7 on 2023-05-02 05:48

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=500, unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(max_length=500, null=True, verbose_name='Page Short Description')),
                ('image', models.ImageField(upload_to='services/%Y/%m/%d/', verbose_name='Image')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=10, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name': 'List Category',
                'verbose_name_plural': 'List Categories',
                'db_table': 'service-category-list',
            },
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Page Title')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description')),
                ('video_url', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=10, verbose_name='Status')),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Keywords')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.category')),
            ],
            options={
                'verbose_name': 'List Services',
                'verbose_name_plural': 'List Services',
                'db_table': 'service-list',
            },
        ),
    ]
