# Generated by Django 4.1.7 on 2023-05-02 05:48

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=500, unique=True, verbose_name='Full Name')),
                ('designation', models.CharField(max_length=500, verbose_name='Designation')),
                ('message', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Message')),
                ('image', models.ImageField(null=True, upload_to='testimonial/%Y/%m/%d/', verbose_name='Image')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=10, verbose_name='Status')),
                ('submission_date', models.DateTimeField(auto_now=True, verbose_name='Submission Date')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'db_table': 'testimonials_list',
            },
        ),
    ]
